name: expo_preview.yml
on: pull_request

jobs:
  preview:
    name: Preview with ExpoGo
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Commenting on PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const iosQrCodeUrl = "https://github.com/${{ github.repository }}/suites/${{ github.run_id }}/artifacts/${{ steps.uploading_qr_code.outputs.artifact_id }}/qr/qr_ios.png";
            const androidQrCodeUrl = "https://github.com/${{ github.repository }}/suites/${{ github.run_id }}/artifacts/${{ steps.uploading_qr_code.outputs.artifact_id }}/qr/qr_android.png";
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
              <h1 align="center">🎉 La preview est prête 🎉</h1>
              
              ![iOS](https://raw.githubusercontent.com/PapillonApp/chat-themes/refs/heads/main/.github/assets/ios_light.png#gh-light-mode-only)
              ![iOS](https://raw.githubusercontent.com/PapillonApp/chat-themes/refs/heads/main/.github/assets/ios_dark.png#gh-dark-mode-only)
              
              <img
              src="http://api.qrserver.com/v1/create-qr-code/?data=exp://expo.godetremy.com/${{ github.event.pull_request.number }}?platform=ios&size=150x150&margin=5"
              align="left"
              />
              Pour exécuter cette preview sur ton iPhone, tu auras besoin de l'application ExpoGo.
              Une fois installée, scanne ce QR code à l'aide de l'appareil photo ou entre cette url dans Expo :
              \`exp://expo.godetremy.com/${{ github.event.pull_request.number }}?platform=ios\`
              
              <br><br><br>
              <hr>
              
              ![Android](https://raw.githubusercontent.com/PapillonApp/chat-themes/refs/heads/main/.github/assets/android_light.png#gh-light-mode-only)
              ![Android](https://raw.githubusercontent.com/PapillonApp/chat-themes/refs/heads/main/.github/assets/android_dark.png#gh-dark-mode-only)
              
              <img
              src="http://api.qrserver.com/v1/create-qr-code/?data=exp://expo.godetremy.com/${{ github.event.pull_request.number }}?platform=android&size=150x150&margin=5"
              align="left"
              />
              Pour exécuter cette preview sur ton téléphone, tu auras besoin de l'application ExpoGo.
              Télécharge-la depuis le Google PlayStore, puis une fois installée, scanne ce QR code à l'aide du scanneur de QR code
              de ton mobile ou entre cette url dans Expo :
              \`exp://expo.godetremy.com/${{ github.event.pull_request.number }}?platform=android\`
              
              <br>
              `
            });
